CREATE TABLE REZISER
(
    BROJ NUMBER(5) CONSTRAINT REZISER_PK PRIMARY KEY,
    IME VARCHAR(30) NOT NULL,
    PREZIME VARCHAR(50),
    GODINA_ROD NUMBER(4) CONSTRAINT REZISER_RODJ_CK CHECK (GODINA_ROD BETWEEN 1880 AND 1980),
    GODINA_SM NUMBER(4) CONSTRAINT REZISER_SM_CK CHECK (GODINA_SM > 1930),
    CONSTRAINT REZISER_GOD_CK CHECK(GODINA_ROD <= GODINA_SM)
);

CREATE TABLE FILM
(
    BROJ NUMBER(5) CONSTRAINT FILM_PK PRIMARY KEY,
    NASLOV VARCHAR(50) NOT NULL,
    TIP VARCHAR(20) NOT NULL,
    AA_NOMINACIJE NUMBER(2),
    AA_NAGRADE  NUMBER(2),
    GODINA NUMBER(4),
    KRITIKA VARCHAR(1000),
    REZISER NUMBER(5) CONSTRAINT FILM_REZISER_FK REFERENCES REZISER,
    BROJ_DISKOVA NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE GLUMAC
(
    IME VARCHAR(30) NOT NULL,
    PREZIME VARCHAR(50),
    BROJ NUMBER(5) NOT NULL,
    GODINA_ROD NUMBER(4) CONSTRAINT GLUMAC_RODJ_CK CHECK (GODINA_ROD BETWEEN 1880 AND 1980),
    GODINA_SM  INTEGER CONSTRAINT GLUMAC_SM_CK CHECK (GODINA_SM > 1930),
    MESTO_ROD VARCHAR(30),
    CONSTRAINT GLUMAC_GOD_CK CHECK (GODINA_ROD <= GODINA_SM),
    CONSTRAINT GLUMAC_PK PRIMARY KEY (BROJ)
);

CREATE TABLE IGRA
(
    FILM NUMBER(5) NOT NULL,
    GLUMAC  NUMBER(5) NOT NULL,
    ULOGA VARCHAR(20) NOT NULL,
    CONSTRAINT IGRA_PK PRIMARY KEY (FILM, GLUMAC),
    CONSTRAINT IGRA_FILM_FK FOREIGN KEY (FILM) REFERENCES FILM(BROJ),
    CONSTRAINT IGRA_GLUMAC_FK FOREIGN KEY (GLUMAC) REFERENCES GLUMAC(BROJ)
);

CREATE TABLE CLAN
(
    IME VARCHAR(30) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    BROJ NUMBER(5),
    ADRESA  VARCHAR(50) NOT NULL,
    BROJ_TELEFONA VARCHAR(20),
    DATUM_UCLANJENJA DATE,
    CONSTRAINT CLAN_PK PRIMARY KEY (BROJ)
);


CREATE TABLE IZNAJMLJIVANJE
(
    BROJ  NUMBER(7),
    FILM NUMBER(5) NOT NULL,
    CLAN  NUMBER(5) NOT NULL,
    DATUM_IZNAJMLJIVANJA DATE NOT NULL,
    DATUM_VRACANJA DATE,
    CONSTRAINT IZNAJMLJIVANJE_PK PRIMARY KEY (BROJ),
    CONSTRAINT IZNAJMLJIVANJE_CLAN_FK FOREIGN KEY (CLAN) REFERENCES CLAN(BROJ),
    CONSTRAINT IZNAJMLJIVANJE_FILM_FK FOREIGN KEY (FILM) REFERENCES FILM(BROJ)
);

